### PR TITLE
send cookies for the current domain 

### PR DESCRIPTION
**Pull request by tlaitinen**
to access vector data at a server requiring cookie-based authentication

### CODE REVIEW

**Comment by tlaitinen** [comment]
I have added `fetchOptions` as an option as suggested.

**Comment by tlaitinen** [comment]
I noticed that I accidentally indented with spaces, too, and pushed another commit to fix it shortly after.

**Comment by perliedman** [comment]
Great work, thanks again for contributing!

**Comment by tlaitinen** [comment]
Happy to help. Thanks for all the work on Leaflet.

**Pull request merged**
